### ISSUE TITLE
Cannot find proj.db when using C# Environment.SetEnvironmentVariable

### ISSUE THREAD

**Issue by ktheijs** [OSGeo/gdal#1647]
## Expected behavior and actual behavior.

I am using GDAL 3.0.0 in C# and I am encountering an issue regarding the new proj.db.
I set both the environment variable and the config option as shown here:
` Environment.SetEnvironmentVariable("PROJ_LIB", <MyPath>);`
`  Gdal.SetConfigOption("PROJ_LIB", <MyPath>);`

However when I try to create a SpatialReference 
`SpatialReference spatialReference = new SpatialReference(csWkt);`
I get the exception "PROJ: proj_create_from_wkt: Cannot find proj.db"

Is an additional step needed to make GDAL find the proj.db file?

## Operating system

Windows 10

## GDAL version and provenance

GDAL 3.0.0

**Comment by rouault** [comment]
Is <MyPath> the name of the directory where proj.db is ?

**Comment by ktheijs** [comment]
Yes it is. So basically the 'proj6/SHARE' folder.

Op vr 14 jun. 2019 17:29 schreef Even Rouault <notifications@github.com>:

**Comment by rouault** [comment]
is the environment variable set before you do any GDAL stuff ? As soon as GDAL has initialized PROJ, the variable might be ignored afterwards.

**Comment by ktheijs** [comment]
Yes setting the environment variables is the first thing I do.

Op vr 14 jun. 2019 18:51 schreef Even Rouault <notifications@github.com>:

**Comment by rouault** [comment]
Can you enable PROJ_DEBUG=5 and report what appears in the standard error stream ?

**Comment by ktheijs** [comment]
I will try it on Monday and I'll get back to you. Thanks for the effort!

Op vr 14 jun. 2019 19:03 schreef Even Rouault <notifications@github.com>:

**Comment by ktheijs** [comment]
I tried setting the variable like this 
`Gdal.SetConfigOption("CPL_DEBUG", "ON");`
`Gdal.SetConfigOption("PROJ_DEBUG", "5");`

I'm not sure if the first line is necessary, but with or without it, I get no additional output in my error stream. Is this the right way to set this value?

**Comment by rouault** [comment]
Ah, for PROJ_DEBUG and PROJ_LIB, they must be defined as operating system environment variables. GDAL config option concept only works for GDAL.

**Comment by ktheijs** [comment]
Okay, good to know. I made the situation as simple as possible. And I still get the same issue.
This is the code that I am running at startup:
`Environment.SetEnvironmentVariable("PATH", path);`
`Environment.SetEnvironmentVariable("PROJ_DEBUG", "5");`
`Environment.SetEnvironmentVariable("PROJ_LIB", projLibDirectoryFullName);`
`SpatialReference s = new SpatialReference("");`
`s.ImportFromEPSG(2353);`

"path" is the correct path to set.
"projLibDirectoryFullName" points to the directory with the proj.db file.

This is the only relevant output I get (which is the same when I don't set the PROJ_DEBUG variable):

> ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
Exception thrown: 'System.ApplicationException' in osr_csharp.dll

**Comment by szekerest** [comment]
It looks like getenv doesn't seem to retrieve PROJ_LIB which has been set with Environment.SetEnvironmentVariable. According to https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getenv-wgetenv?view=vs-2019  "getenv and _putenv use the copy of the environment pointed to by the global variable _environ to access the environment. getenv operates only on the data structures accessible to the run-time library and not on the environment "segment" created for the process by the operating system." We should probably find another way to specify the search location, using getenv is fragile because it depends on the time of the CRT initialization. Probably exposing OSRSetPROJSearchPaths would help.

**Comment by szekerest** [comment]
Just tried exposing OSRSetPROJSearchPaths and it was working. 
However it seems that proj is using that option as the last resort after trying to open a hardcoded proj_lib_name. It would be reasonable to test against search_paths in proj6 earlier or have GDAL to use other options (like setting  the file_finder) to achieve the same result.

**Comment by ktheijs** [comment]
Is there anything I can do for now, or should I wait until there is a fix released on your side?

**Comment by rouault** [comment]
https://stackoverflow.com/questions/4788398/changes-via-setenvironmentvariable-do-not-take-effect-in-library-that-uses-geten confirms the issue pointed by @szekerest and suggests a workaround.

**Comment by szekerest** [comment]
@rouault Yes, but I still can't imagine why the same approach was working with GDAL-2.4+proj4 and doesn't work with GDAL-3.0+proj6. Probably there has been a change how the proj lib is being loaded by GDAL?

**Comment by rouault** [comment]
> Probably there has been a change how the proj lib is being loaded by GDAL?

That depends on how GDAL was built in GDAL <= 2.4. If it wasn't built with -DPROJ_STATIC (and thus through LoadLibrary("proj.dll")), then yes, it might be a relevant difference. In GDAL 3.0, PROJ is always linked in a classic way to GDAL.

**Comment by rouault** [comment]
https://github.com/OSGeo/gdal/pull/1658 shoud hopefully fix the issue by adding a osr.SetPROJSearchPath() method. I can't test C# , but at least that works for Python

**Comment by rouault** [comment]
I've merged #1658 in master and backported in release/3.0 as well.  Search paths are taken into priority over PROJ_LIB or the hard-coded string (on Unix builds) starting with PROJ 6.1

**Comment by ktheijs** [comment]
@szekerest Are you planning on updating the stable release on gisinternals any time soon? It would be great if I could test this fix and all the other bug fixes) in C#.

**Comment by szekerest** [comment]
yes, I'll be trying to update it in this week

**Comment by ktheijs** [comment]
Great! Thanks.

**Comment by ktheijs** [comment]
@szekerest, could you also tell me if the following things will be included? 
* The fix for this issue
* OSR.GetCRSInfoListFromDatabase as in #1273. 
* GDAL.Dataset.GetSpatialRef()

Those would be pretty useful.

**Comment by Otiel** [comment]
I'm getting the same error using the 3.0.4 gisinternals release.

@szekerest Can you confirm if this fix is supposed to have been included?

**Comment by makoychan** [comment]
was there any solution for this? i am using the 3.2.0 and i also get the same problem when using the c# dlls and doign importfrompseg   i have everything installed on program files/gdal and the exe on the folders are working.. but referencing these dlls and trying that method still throw be that error cannot find proj.db... all env virables are set.. i even check it with Gdal.GetConfigOption("PROJ_LIB", ""); and im getting the correct path of the proj.db ... any help?

**Comment by ktheijs** [comment]
@makoychan did you also use Osr.SetPROJSearchPath() to point to your 'proj6' folder? That was the fix for me.
