### ISSUE TITLE
vsicurl fails when the file size can't be detected

### ISSUE THREAD

**Issue by Kodiologist** [OSGeo/gdal#1716]
Or at least, I think that's what the underyling issue is. The specific problem is that downloading a zipped US Census shapefile with `curl` and reading it with `vsizip` works fine, but stacking `vsizip` with `vsicurl` doesn't (although it works with the example in the documentation, `/vsizip//vsicurl/https://raw.githubusercontent.com/OSGeo/gdal/master/autotest/ogr/data/poly.zip`). Compare:

```
$ curl 'https://www2.census.gov/geo/tiger/TIGER2010BLKPOPHU/tabblock2010_36_pophu.zip' --output tabblock2010_36_pophu.zip
$ ogrinfo -ro -al -so '/vsizip/tabblock2010_36_pophu.zip'
INFO: Open of `/vsizip/tabblock2010_36_pophu.zip'
      using driver `ESRI Shapefile' successful.

Layer name: tabblock2010_36_pophu
Metadata:
  DBF_DATE_LAST_UPDATE=2011-04-01
…
$ ogrinfo -ro -al -so --debug on '/vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2010BLKPOPHU/tabblock2010_36_pophu.zip'
GNM: GNMRegisterAllInternal                    
GNM: RegisterGNMFile                           
GNM: RegisterGNMdatabase                       
VSICURL: GetFileSize(https://www2.census.gov/geo/tiger/TIGER2010BLKPOPHU/tabblo
ck2010_36_pophu.zip)=0  response_code=200
VSICURL: Request at offset 0, after end of file
VSICURL: Request at offset 0, after end of file
VSICURL: Request at offset 0, after end of file
… [ Repeated many times ]
VSICURL: Request at offset 0, after end of file                                
VSICURL: Request at offset 0, after end of file                                
FAILURE:                                                                       
Unable to open datasource `/vsizip//vsicurl/https://www2.census.gov/geo/tiger/T
IGER2010BLKPOPHU/tabblock2010_36_pophu.zip' with the following drivers.
…
```

See also [this question on gis.SE](https://gis.stackexchange.com/questions/326773/importing-shapefile-from-website-if-download-link-is-compressed-file).

I'm running GDAL 2.2.3 on Ubuntu 18.04, 64-bit. I tried building GDAL 3.0.1 to test this issue there, but I got `configure: error: PROJ 6 symbols not found` and I don't know which Ubuntu package I need for that. (A file with build instructions would be helpful.)

**Comment by rouault** [comment]
This has been fixed in GDAL 3.0.1 per e3b9cb3fe73b177191085a02993c0a9aacb6b4ce
There are a number of Docker images in https://github.com/OSGeo/gdal/tree/master/gdal/docker which you can use directly or take inspiration from to build your own GDAL

**Comment by Kodiologist** [comment]
Sorry, thanks.

**Comment by mchibok** [comment]
I think the problem is still present on Windows, GDAL 3.4.3.

using documentation test file from https://raw.githubusercontent.com/OSGeo/gdal/master/autotest/ogr/data/shp/poly.zip works fine:
ogrinfo -ro -al -so --debug ON /vsizip//vsicurl/https://raw.githubusercontent.com/OSGeo/gdal/master/autotest/ogr/data/shp/poly.zip
GDAL: Auto register ...
...
VSICURL: GetFileSize(https://raw.githubusercontent.com/OSGeo/gdal/master/autotest/ogr/data/shp/poly.zip)=2483  response_code=200
VSICURL: Downloading 0-2482 (https://raw.githubusercontent.com/OSGeo/gdal/master/autotest/ogr/data/shp/poly.zip)...
VSICURL: Got response_code=206
GDAL: GDALOpen(/vsizip//vsicurl/https://raw.githubusercontent.com/OSGeo/gdal/master/autotest/ogr/data/shp/poly.zip, this=00000141418407D0) succeeds as ESRI Shapefile.     
INFO: Open of `/vsizip//vsicurl/https://raw.githubusercontent.com/OSGeo/gdal/master/autotest/ogr/data/shp/poly.zip'
      using driver `ESRI Shapefile' successful.
OGR: GetLayerCount() = 1
`

but not from an open data website https://data.montreal.ca/dataset/b628f1da-9dc3-4bb1-9875-1470f891afb1/resource/674c2a18-e013-42ca-bfa6-3bb7358e820d/download/limites-terrestres.zip (425kb).

`
ogrinfo -ro -al -so --debug ON /vsizip//vsicurl/https://data.montreal.ca/dataset/b628f1da-9dc3-4bb1-9875-1470f891afb1/resource/674c2a18-e013-42ca-bfa6-3bb7358e820d/download/limites-terrestres.zip
GDAL: Auto register C:\OSGeo4W\bin\gdalplugins\gdal_ECW_JP2ECW.dll using GDALRegister_ECW_JP2ECW.
GDAL: Auto register C:\OSGeo4W\bin\gdalplugins\gdal_GEOR.dll using GDALRegister_GEOR.
GDAL: Auto register C:\OSGeo4W\bin\gdalplugins\gdal_HDF5.dll using GDALRegister_HDF5.
GDAL: Auto register C:\OSGeo4W\bin\gdalplugins\gdal_MG4Lidar.dll using GDALRegister_MG4Lidar.
GDAL: Auto register C:\OSGeo4W\bin\gdalplugins\gdal_MrSID.dll using GDALRegister_MrSID.
GDAL: Auto register C:\OSGeo4W\bin\gdalplugins\ogr_OCI.dll using RegisterOGROCI.
GDAL: Auto register C:\OSGeo4W\bin\gdalplugins\ogr_SOSI.dll using RegisterOGRSOSI.
HTTP: libcurl/7.75.0 OpenSSL/1.1.1o zlib/1.2.12 WinIDN
VSICURL: HEAD did not provide file size. Retrying with GET
VSICURL: GetFileSize(https://data.montreal.ca/dataset/b628f1da-9dc3-4bb1-9875-1470f891afb1/resource/674c2a18-e013-42ca-bfa6-3bb7358e820d/download/limites-terrestres.zip): 
response_code=200, msg=Failure writing output to destination
VSICURL: Request at offset 0, after end of file
VSICURL: Request at offset 0, after end of file
... (repeated multiple times)
FAILURE:
Unable to open datasource `/vsizip//vsicurl/https://data.montreal.ca/dataset/b628f1da-9dc3-4bb1-9875-1470f891afb1/resource/674c2a18-e013-42ca-bfa6-3bb7358e820d/download/limites-terrestres.zip' with the following drivers.
...
`

I have tried with ogrinfo in the OSGeo4W (3.4.3) and PostgreSQL (3.4.2) folders.

**Comment by rouault** [comment]
> , but I guess something must have changed because a couple months back I was able to use vsizip/vsicurl

Probably on the server side. I've just tested with GDAL 3.4 and 3.4 and get the same error
