### ISSUE TITLE
'Argument list too long' while running make in directory with long path

### ISSUE THREAD

**Issue by Kyeiv** [OSGeo/gdal#2909]
my path to gdal sources:
/home/kyeiv/some-directory/temporary-build/dirwithhash-7bbb521ad2344966b02342a57a85e234c4935h2b/gdal
after running:
./configure
make
i got:
make[1]: execvp: /bin/bash: Argument list too long
make[1]: *** [GNUmakefile:66: libgdal.la] Error 127

the version i am building is 2.4.4

**Comment by rouault** [comment]
I believe this has been fixed in 3.1.0 per 554656a26f248760c7ad64e1b196b47241fc0bb7

**Comment by Kyeiv** [comment]
unfortunately applying this fix is not working and the error still occurs

**Comment by Kyeiv** [comment]
i have also applied https://github.com/OSGeo/gdal/pull/2077/commits/c04eb5a24b2dda757e8f666343c80f9238f35fec but it led to error:
make[1]: *** No rule to make target 'apps/gdalmdiminfo_lib.lo', needed by 'libgdal.la'. Stop.

**Comment by shawnlaffan** [comment]
@Kyeiv - what system are you building on?  e.g., Linux, Mac, MSYS2? 

554656a26f248760c7ad64e1b196b47241fc0bb7 is needed for systems like MSYS2 or cygwin where the maximum command length is 32000 chars.  c04eb5a24b2dda757e8f666343c80f9238f35fec should be sufficient for most other systems.  

After applying the two patches did you ```make clean``` before running ```make```?  (Although if you are using a downloaded tarball then it's probably simpler to unpack to a fresh directory, apply the patches and then build).

If that does not fix the problem then check the length of the commands in the build log, and compare them with your system limits to see which one fails.

**Comment by jratike80** [comment]
@Kyeiv Do you have any news about this?

**Comment by Kyeiv** [comment]
@jratike80 sorry, i don't remember now but it seems like a patch from the newer versions did the job.

**Comment by jratike80** [comment]
Ok, I trust you and close the ticket.
