### ISSUE TITLE
JSON test spins forever

### ISSUE THREAD

**Issue by craigds** [OSGeo/gdal#999]
## Expected behavior and actual behavior.

While fiddling with the test runner I've found `test_ogr_geojson_20` appears to hang forever. This is on a freshly-created vagrant VM from the vagrantfile included with gdal.

## Steps to reproduce the problem.

A slightly reduced version that also fails is:

```python
from osgeo import gdal, ogr

gj = 'autotest/ogr/data/test_type_promotion.json'

# create tmp file with no file extension
data = open(gj, 'rb').read()

f = gdal.VSIFOpenL('/vsimem/testgj', 'wb')
gdal.VSIFWriteL(data, 1, len(data), f)
gdal.VSIFCloseL(f)

# hangs forever, 100% cpu
ds = ogr.Open('/vsimem/testgj')
ds = None

gdal.Unlink('/vsimem/testgj')
```

## Operating system

Ubuntu 14.04 64 bit

## GDAL version and provenance

master @ af8ea0a106e20ed17436d50e333464b85d6553d5

**Comment by craigds** [comment]
`test_ogr_geojson_63` and `test_ogr_geojson_append_flush` do the same thing.

**Comment by rouault** [comment]
I can't reproduce the hang. I did (on a completely fresh new clone)
```
vagrant up
vagrant ssh
cd gnumake-build-gcc4.8
. scripts/setdevenv.sh 
cd /vagrant/autotest/ogr
python ogr_geojson.py
```

**Comment by craigds** [comment]
_interesting_. I suppose it's possible this was caused by something in my pytest branch changes, though I'm at a loss for what it could be. The reduced snippet I pasted above doesn't import anything test-related apart from loading the JSON file from the test directory.

I'll try to narrow it down a bit.

**Comment by craigds** [comment]
aha, it looks like this was actually fixed in a96ea6305efa141059aaef827bdbf12c90bdfbc8. So not pytest-related, I just needed to update (I had avoided updating previously due to #1001.)

**Comment by rouault** [comment]
I doubt this was related to https://github.com/OSGeo/gdal/commit/a96ea6305efa141059aaef827bdbf12c90bdfbc8: this one makes the json parser just more pedantic, but this didn't really fix a potential infinite loop

**Comment by craigds** [comment]
I did a git bisect and turned up that commit as the fix
